# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pips', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tweet',
            new_name='Pip',
        ),
    ]
